### ISSUE TITLE
Setting the frequency and command list.

### ISSUE THREAD

**Issue by sandmix** [dimhoff/ser4010#4]
Hi, I didn't find what commands can be used to comunicate with the chip. Can you please provide command list, I want to be able to set the frequesncy. Also why it isn't possible to use it on different frequensies I want to be able to use it under 100 Mhz. Thank .

**Comment by dimhoff** [comment]
This is not an issue with this software, but an issue with the user not being capable enough.
Command list is normally not needed. If you still want to directly communicate to the chip, you should be able to at least read a simple C header file.

Changing the frequency is really the most simplest of actions you have to take to use ser4010. If this already proves difficult, then this project is no use to you. This is not a problem with the project but with you.

**Comment by sandmix** [comment]
It's not an issue, but this is only place I found to write the comments. I check the header was able to find the way to set the frequency, I was thinking that it would be good to have list of commands in readme file. Thanks.
